using Scalar.AspNetCore;

namespace Querio.Api.Extensions;

internal static class OpenApiExtensions
{
    private const string DocumentName = "v1";

    public static WebApplicationBuilder AddQuerioOpenApi(this WebApplicationBuilder builder)
    {
        builder.Services.AddOpenApi(DocumentName, options =>
        {
            options.AddDocumentTransformer((document, _, _) =>
            {
                document.Info = new()
                {
                    Title = "Querio API",
                    Version = DocumentName,
                    Description = "Multi-tenant RAG knowledge assistant. Answers are grounded in tenant-owned documents.",
                };

                return Task.CompletedTask;
            });
        });

        return builder;
    }

    /// <summary>
    /// Exposed outside Development only when <c>OpenApi:ExposePublicly</c> is set, so the
    /// hosted demo can show the reference without it being on by accident in production.
    /// </summary>
    public static WebApplication UseQuerioOpenApi(this WebApplication app)
    {
        var exposePublicly = app.Configuration.GetValue<bool>("OpenApi:ExposePublicly");

        if (!app.Environment.IsDevelopment() && !exposePublicly)
        {
            return app;
        }

        app.MapOpenApi();

        app.MapScalarApiReference(options => options
            .WithTitle("Querio API")
            .WithTheme(ScalarTheme.BluePlanet));

        // Swagger UI renders the same document. Swashbuckle is present as a viewer only —
        // the document itself is generated by Microsoft.AspNetCore.OpenApi, so there is no
        // second source of truth to drift.
        app.UseSwaggerUI(options =>
        {
            options.SwaggerEndpoint($"/openapi/{DocumentName}.json", "Querio API v1");
            options.DocumentTitle = "Querio API";
            options.RoutePrefix = "swagger";
        });

        // The root of an API is otherwise a 404, which reads as "the server is broken" when
        // someone opens the base URL to check it is alive.
        app.MapGet("/", () => Results.Redirect("/swagger"))
            .ExcludeFromDescription();

        return app;
    }
}
